#!/usr/bin/env python3
"""
tools/overlay/gen_splat_yaml.py — Generate per-overlay splat YAML configs.

Reads every AREA*.BIN from extract/OVERLAY/, parses its MWo3 header,
and writes a splat YAML to config/overlays/<AREA>.yaml.

Usage:
    python3 tools/overlay/gen_splat_yaml.py [--area AREA18] [--all]

Run from the repo root.  Requires the overlays to be extracted first:
    python3 tools/overlay/extract_overlays.py   (or extract manually)
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OVERLAY_DIR = ROOT / "extract" / "OVERLAY"
CONFIG_OUT = ROOT / "config" / "overlays"
HEADER_SIZE = 0x40
ARENA_BASE = 0x00823500
GP_VALUE = 0x0027D370


def parse_header(data: bytes) -> dict:
    if len(data) < HEADER_SIZE:
        raise ValueError(f"File too short: {len(data)}")
    if data[0:4] != b'MWo3':
        raise ValueError(f"Bad magic: {data[0:4]!r}")
    u32 = lambda o: struct.unpack_from('<I', data, o)[0]
    return {
        'overlay_id':             u32(0x04),
        'load_address':           u32(0x08),
        'text_size':              u32(0x0C),
        'data_size':              u32(0x10),
        'bss_size':               u32(0x14),
        'static_init_address':    u32(0x18),
        'static_init_end_address':u32(0x1C),
        'overlay_name':           data[0x20:0x40].rstrip(b'\x00').decode('ascii', errors='replace'),
    }


def gen_yaml(name: str, hdr: dict, bin_path: Path) -> str:
    """
    Generate a splat YAML for one overlay.

    The overlay binary layout (as a flat file, not an ELF):
      [0x00..0x3F]   64-byte MWo3 header  — skip (type: databin)
      [0x40..0x40+text_size)  .text        — vram 0x823500
      [0x40+text_size..)      .data        — vram 0x823500+text_size

    splat's 'start' field is the file offset (in bytes) of the segment.
    'vram' is the corresponding virtual address.

    Symbol-name prefix: overlay_AREAXX_ — avoids collisions across overlays
    that all share vram 0x823500.
    """
    ts = hdr['text_size']
    ds = hdr['data_size']
    bs = hdr['bss_size']
    load = hdr['load_address']   # always 0x823500

    # File offsets:
    text_file_start = HEADER_SIZE             # 0x40
    data_file_start = HEADER_SIZE + ts        # 0x40 + text_size
    eof_offset      = HEADER_SIZE + ts + ds   # = len(data)

    # vram addresses:
    text_vram = load                           # 0x823500
    data_vram = load + ts
    bss_vram  = load + ts + ds

    # sha1 of the original binary — splat can verify it if desired.
    # We skip sha1 here (user rebuilds; we don't want to bake disc bytes in config)
    # so no sha1 line in the YAML.

    # Build the YAML text
    yaml = f"""\
# splat config for overlay {name} (overlay_id={hdr['overlay_id']})
# Auto-generated by tools/overlay/gen_splat_yaml.py — do not edit by hand.
# Original file: extract/OVERLAY/{name}.BIN
#
# MWo3 header summary:
#   overlay_id     : {hdr['overlay_id']}
#   load_address   : 0x{load:08x}
#   text_size      : 0x{ts:x}  ({ts} bytes)
#   data_size      : 0x{ds:x}  ({ds} bytes)
#   bss_size       : 0x{bs:x}  ({bs} bytes)
#   overlay_name   : {hdr['overlay_name']!r}

name: "{name}"

options:
  platform: ps2
  basename: {name}
  base_path: ../..       # repo root (relative to config/overlays/)
  target_path: extract/OVERLAY/{name}.BIN

  asm_path: build/overlays/{name}/asm
  src_path: src/overlays/{name}
  build_path: build/overlays/{name}
  ld_script_path: build/overlays/{name}/{name}.ld
  generated_asm_macros_directory: build/overlays/{name}
  undefined_funcs_auto_path: build/overlays/{name}/undefined_funcs_auto.txt
  undefined_syms_auto_path:  build/overlays/{name}/undefined_syms_auto.txt

  compiler: MWCCPS2
  gp_value: 0x{GP_VALUE:08x}

  # Per-overlay symbol prefix to avoid vram collisions between overlays.
  # All overlays load at 0x823500; prefix scopes names to this overlay.
  symbol_name_format: "overlay_{name}_$VRAM"

  symbol_addrs_path:
    - config/overlays/{name}_symbol_addrs.txt

  create_c_files: False
  disassemble_all: True
  section_order: [".text", ".data", ".rodata", ".bss"]
  subalign: 2

segments:
  # MWo3 header (0x40 bytes) — binary blob, not code.
  - name: {name}_header
    type: databin
    start: 0x0

  # .text + .data section (code segment): file 0x{text_file_start:x}..0x{eof_offset:x}
  #                                         vram 0x{text_vram:08x}..0x{bss_vram:08x}
  - name: {name}
    type: code
    start: 0x{text_file_start:x}
    vram: 0x{text_vram:08x}
    bss_size: 0x{bs:x}
    subsegments:
      - [0x{text_file_start:x}, c, {name}/code]
"""
    if ds > 0:
        yaml += f"""\
      - [0x{data_file_start:x}, .data]
"""

    yaml += f"""
  # End of file.
  - [0x{eof_offset:x}]
"""
    return yaml


def gen_symbol_addrs(name: str, hdr: dict) -> str:
    """Generate a symbol_addrs file for an overlay with the entry-point stub.

    splat 0.40 does not support # comment lines in symbol_addrs files —
    every non-empty line must be a symbol definition with exactly one semicolon.
    We define only the overlay entry point (load_address+0x40) so splat
    can name the first real function correctly.
    """
    load = hdr['load_address']
    entry_vram = load + 0x40   # 0x00823540 for all overlays
    return f"overlay_{name}_func_{entry_vram:08X} = 0x{entry_vram:08X}; // type:func\n"


def process_overlay(bin_path: Path) -> None:
    name = bin_path.stem  # e.g. "AREA18"
    data = bin_path.read_bytes()
    hdr = parse_header(data)

    CONFIG_OUT.mkdir(parents=True, exist_ok=True)

    yaml_path = CONFIG_OUT / f"{name}.yaml"
    yaml_path.write_text(gen_yaml(name, hdr, bin_path))
    print(f"  wrote {yaml_path.relative_to(ROOT)}")

    sym_path = CONFIG_OUT / f"{name}_symbol_addrs.txt"
    # Always write — ensures the entry-point stub is present (splat requires
    # at least one real symbol with a semicolon).
    sym_path.write_text(gen_symbol_addrs(name, hdr))
    print(f"  wrote {sym_path.relative_to(ROOT)}")


def main():
    ap = argparse.ArgumentParser(description="Generate per-overlay splat YAML configs")
    ap.add_argument("--area", help="Process only this area (e.g. AREA18)")
    ap.add_argument("--all", action="store_true", help="Process all overlays (default)")
    args = ap.parse_args()

    if not OVERLAY_DIR.exists():
        sys.exit(f"error: {OVERLAY_DIR} not found. Extract overlays first.")

    bins = sorted(OVERLAY_DIR.glob("AREA*.BIN"))
    if not bins:
        sys.exit(f"error: no AREA*.BIN files found in {OVERLAY_DIR}")

    if args.area:
        name = args.area.upper()
        bins = [b for b in bins if b.stem == name]
        if not bins:
            sys.exit(f"error: {name}.BIN not found in {OVERLAY_DIR}")

    for b in bins:
        print(f"Processing {b.name} ...")
        try:
            process_overlay(b)
        except Exception as e:
            print(f"  ERROR: {e}", file=sys.stderr)

    print(f"\nDone. {len(bins)} overlay(s) processed.")
    print(f"Configs written to {CONFIG_OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
