#!/usr/bin/env python3
"""Assemble all 3149 boot-ELF functions into build/filler/*.o for linking.

For each function that is NOT covered by a compiled build/obj/*.o:
  • Assemble its splat-generated .s file (build/asm/matchings/main/code/<name>.s)
    into build/filler/<name>.o using mipsel-linux-gnu-as -march=r5900.
  • Strip any empty .text/.data/.bss sections that mwldmips rejects.

For each function that IS covered by a compiled build/obj/*.o (our decompiled
C, or an asm-matched .c wrapper):
  • Copy it to build/filler/<name>.o and strip empty sections there too,
    so the linker can pull everything from one flat directory.

The result is a build/filler/ directory containing one .o per function,
covering all 3149 boot-ELF functions, ready for mwldmips.

Usage (run INSIDE the exterm-toolchain container, repo at /work):
    python3 tools/decomp/fill_unmatched.py [--jobs N] [--clean]

Outside the container (via Apple `container` CLI):
    container run --rm -v "$PWD:/work" -w /work exterm-toolchain \\
        python3 tools/decomp/fill_unmatched.py

The script is idempotent — re-running only rebuilds stale or missing objects.
Pass --clean to wipe build/filler/ first.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASM_DIR = ROOT / "build" / "asm" / "matchings" / "main" / "code"
OBJ_DIR = ROOT / "build" / "obj"
FILLER_DIR = ROOT / "build" / "filler"
STRIP_SCRIPT = ROOT / "tools" / "decomp" / "strip_sections.py"

# Assembler invocation (same flags as build.py's assemble_cmd).
# -march=r5900 sets the EE flag so mipsel-linux-gnu-readelf/objcopy handle
# EE-specific instructions correctly.
AS_CMD = [
    "mipsel-linux-gnu-as",
    "-march=r5900",
    str(ROOT / "config" / "asm_prelude.inc"),
    str(ROOT / "build" / "macro.inc"),
]

# Functions that must be assembled with -L (keep local labels) and then have
# all .L* labels globalized, because branches from OTHER functions reference
# labels defined inside these functions' .s files.  Without this the linker
# would see undefined .L00XXXXXX references.
CROSS_LABEL_FUNCS = {
    "func_00140004",
    "func_001C0004",  # defines .L001C02B4 referenced from func_001BFFD0
    "func_001C2FF0",
    "func_00200004",
    "func_00201000",
}

# Functions that have R_MIPS_GPREL16 relocations in their build/obj/*.o (mwcc
# compiled) that overflow the ±32KB $gp window at link time.  We fall back to
# assembling from the splat .s instead, which uses LUI+ADDIU (no GP-relative).
# This list was generated by running mwldmips and collecting all GP overflow errors.
GPREL_FORCE_ASM = {
    # Original 4 (identified in first link attempt):
    "func_00102600",
    "func_0011FD78",
    "func_00120AD0",
    "func_001B0070",
    # Additional 107 discovered in subsequent link (obj/ compiled with GP-relative):
    "func_001289C0",
    "func_00128C10",
    "func_0012A5D0",
    "func_0012E560",
    "func_00131740",
    "func_001333F0",
    "func_00133FD0",
    "func_00137920",
    "func_00138540",
    "func_0013D490",
    "func_00140760",
    "func_001418F0",
    "func_00141F00",
    "func_001434C0",
    "func_00145210",
    "func_001469B0",
    "func_001475A0",
    "func_0014BB10",
    "func_0014C2E0",
    "func_0014D3B0",
    "func_0014D7C0",
    "func_0014ED10",
    "func_0014FBC0",
    "func_001516B0",
    "func_00153770",
    "func_00153A10",
    "func_00154040",
    "func_00154740",
    "func_00158810",
    "func_00158EC0",
    "func_00159210",
    "func_00159620",
    "func_00159970",
    "func_00159B90",
    "func_0015A070",
    "func_0015AC00",
    "func_0015C420",
    "func_00161790",
    "func_001647D0",
    "func_0016D130",
    "func_00173E60",
    "func_00180850",
    "func_00181730",
    "func_0018ABA0",
    "func_00198440",
    "func_001BB520",
    "func_001BBDA0",
    "func_001BC960",
    "func_001BD9F0",
    "func_001BDFC0",
    "func_001BE6C0",
    "func_001BECC0",
    "func_001BF3C0",
    "func_001BF6B0",
    "func_001C0004",
    "func_001C02E0",
    "bone_root_pulse",  # was func_001C06E0
    "func_001C1A80",
    "func_001CB9B0",
    "func_001D0F20",
    "func_001D1C50",
    "func_001D1F20",
    "func_001D1F80",
    "func_001D1FF0",
    "func_001D2040",
    "vif_append_ref_tag",  # was func_001D2090
    "func_001D21E0",
    "func_001D2300",
    "func_001D3F60",
    "func_001D40E0",
    "func_001D4440",
    "func_001D49D0",
    "func_001D8130",
    "func_001D8340",
    "func_001D8690",
    "func_001D88B0",
    "func_001D89D0",
    "func_001DA6A0",
    "func_001DD7B0",
    "func_001DDB70",
    "func_001DDE10",
    "func_001DE920",
    "func_001DF180",
    "func_001DF600",
    "func_001DFA40",
    "func_001E1E60",
    "func_001E7D20",
    "func_001E9280",
    "func_001E9E60",
    "func_001FCBD0",
    "func_001FCE30",
    "func_001FD950",
    "func_001FE6B0",
    "func_001FE7C0",
    "func_001FE8D0",
    "func_001FEE60",
    "func_00206BF0",
    "func_00207350",
    "func_00207BB0",
    "func_00207D00",
    "func_002134C0",
    "func_00219550",
    "func_0021B180",
    "func_0021B550",
    "func_0021B840",
    "func_00228C90",
    "func_002293B0",
    # Additional gprel overflow found after the 2026-05-24 naming/splat-regen pass:
    "func_00122BA8",
    "func_00187EC0",
    "func_001D1C10",
    "func_001DB240",
    "func_001DB800",
    "func_001FAB50",
    "func_001FAB80",
    "func_001FF080",
    "func_00207070",
    "func_0020E080",
}

# Symbols in these objects that must be weakened to avoid multiply-defined
# errors when the same symbol is also declared as a BSS global in a compiled
# src/*.c file.  Maps object-stem → list of symbol names to weaken.
WEAKEN_SYMBOLS: dict[str, list[str]] = {
    "func_00271DF8": ["D_00275670"],
}

# Functions whose build/obj/*.o has a size mismatch vs the original function.
# These were compiled by mwcc but the compiler dropped or added instructions
# (e.g. dead-store elimination of delay-slot daddu zeroing, or extra prologue).
# We fall back to assembling from the splat .s (which contains the exact original
# bytes) to obtain the correct .text size and content.
SIZE_DRIFT_FORCE_ASM = {
    "func_00100610",
    "func_001046C0",
    "func_00108EA8",
    "func_00108FF8",
    "func_0010C0C8",
    "func_0010C200",
    "func_0010C290",
    "func_0010C2F8",
    "func_0010C360",
    "func_0010C3C8",
    "func_0010C430",
    "func_0010C4A0",
    "func_0010D098",
    "func_0010E368",
    "func_00110C80",
    "func_00110D70",
    "func_00110E58",
    "func_00119870",
    "func_00119880",
    "func_0011B390",
    "func_0011B410",
    "func_0011BCF8",
    "func_0011C128",
    "func_0011DE90",
    "func_0011E148",
    "func_0011E2A8",
    "func_00127650",
    "func_00128250",
    "func_0012B850",
    "func_0012D850",
    "func_0012F980",
    "func_00131510",
    "func_00131940",
    "func_00133A20",
    "func_00137830",
    "func_0013B790",
    "func_0013BA20",
    "func_0013BBB0",
    "func_0013D850",
    "func_0013DC60",
    "func_00141A30",
    "func_00142330",
    "func_0014ACC0",
    "func_0014BE20",
    "func_0014C220",
    "func_0014E420",
    "func_0014E670",
    "func_0014EC00",
    "func_0014EEF0",
    "func_00150260",
    "func_001504D0",
    "func_00150DA0",
    "func_00151590",
    "func_00152930",
    "func_00152B60",
    "func_00152EB0",
    "func_00153950",
    "func_00158130",
    "func_0015B030",
    "func_0015B610",
    "func_0015D460",
    "func_001639E0",
    "func_00163B40",
    "func_00163C10",
    "func_00163D50",
    "func_001645D0",
    "func_0016AC50",
    "func_00177460",
    "func_00178390",
    "func_001796C0",
    "func_0017D800",
    "func_0017D940",
    "func_0017DAF0",
    "func_0017DC80",
    "func_0017DEB0",
    "func_0017DFB0",
    "func_001811F0",
    "func_00181430",
    "func_00182100",
    "func_00182430",
    "func_00182870",
    "func_00183250",
    "func_001837B0",
    "func_0018C4B0",
    "func_0018C6A0",
    "func_0018C850",
    "func_0018C920",
    "func_00191120",
    "func_00192010",
    "func_0019A310",
    "func_0019ED80",
    "func_0019F330",
    "func_001A4D10",
    "func_001A58B0",
    "func_001A9E00",
    "func_001AA2A0",
    "func_001AD140",
    "func_001AEB60",
    "func_001AEBA0",
    "func_001B0FD0",
    "func_001B1190",
    "func_001B12B0",
    "func_001B1B70",
    "func_001B1EA0",
    "func_001B2B80",
    "func_001B2BF0",
    "anim_clip_init",  # was func_001C67E0
    "func_001C8710",
    "func_001C9E40",
    "func_001CBE10",
    "func_001CF470",
    "func_001D0D60",
    "func_001DEEE0",
    "func_001E2270",
    "func_001F1110",
    "func_001F5490",
    "func_001FBD50",
    "func_001FBDB0",
    "func_001FBE80",
    "func_001FE530",
    "func_00204700",
    "func_00204AE0",
    "func_00204D60",
    "func_00205F90",
    "func_0021BE40",
    "func_0021BED0",
    "func_0021D1A0",
    "func_0021D490",
    "func_0021D4E0",
    "func_0021D6C0",
    "func_0021E490",
    "func_00224290",
    "func_002243F0",
    "func_00225570",
    "func_00229960",
    "func_00229A00",
    "func_00229C00",
    # Content-mismatch functions: compiled obj has wrong instructions (different
    # code generation from mwcc vs original), even though size may be correct.
    # These were identified by comparing filler object bytes to the original ELF.
    "func_00100550",
    "func_0010BFB0",
    "func_0011B1E0",
    "func_0011E878",
    "func_001226E8",
    "func_00193D90",
    "func_001AFF90",
    "func_001B3250",
    "func_001B3670",
    "func_001B5F40",
    "anim_decode_translation",  # was func_001C85D0
    "func_001D2160",
    "func_001D2DE0",
    "func_001D8FD0",
    "func_001DCFF0",
    "func_001DEDB0",
    "func_001E0C80",
    "func_001FE660",
    "func_00206970",
    # 91 additional drift/content-mismatch entries found after the
    # 2026-05-24 naming/splat-regen pass.  These all have src/*.c that
    # mwcc compiles successfully (or that build.py's tolerant compile
    # batches skip) but whose bytes diverge from the original; fall back
    # to splat-assembled .s for byte identity.
    "dmac_channel_base",  # was func_00101BB8
    "func_00101CC0",
    "func_00101EA8",
    "func_00102458",
    "func_00102628",
    "func_00102678",
    "func_00103380",
    "func_001063B8",
    "func_00107CB8",
    "func_001098E0",
    "func_00109BC0",
    "func_0010A1B0",
    "func_0010A368",
    "func_0010AD48",
    "func_0010AD58",
    "func_0010AD68",
    "func_0010AD78",
    "func_0010C9C8",
    "func_0010D970",
    "func_0010DC78",
    "func_0010DC90",
    "func_0010DCA8",
    "func_0010DCD8",
    "func_0010E248",
    "func_0010EFA8",
    "func_00110BC0",
    "func_00110C48",
    "func_00112120",
    "func_001145A0",
    "func_00114220",
    "func_00114448",
    "func_001152B0",
    "func_001157F0",
    "func_001199F0",
    "func_00119400",
    "func_00119D08",
    "func_00119D38",
    "func_0011A730",
    "func_0011A938",
    "func_00120038",
    "func_00120048",
    "func_00120B10",
    "func_00122BB8",
    "func_001287F0",
    "func_00128390",
    "func_00128600",
    "func_0012E070",
    "func_0014D1E0",
    "func_0016ADE0",
    "func_001749A0",
    "func_0017B460",
    "func_001899C0",
    "func_0018A880",
    "func_00191350",
    "func_001ACE70",
    "func_001AB650",
    "func_001AB740",
    "func_001AF690",
    "func_001AF890",
    "func_001AFE60",
    "func_001AFF10",
    "func_001B0BA0",
    "func_001B0C60",
    "func_001B6E40",
    "func_001B6F80",
    "func_001BA1C0",
    "func_001BA510",
    "func_001BBD20",
    "func_001BEAC0",
    "func_001C47E0",
    "func_001C5C50",
    "func_001CB8A0",
    "func_001D38A0",
    "func_001D4A90",
    "func_001D4E20",
    "func_001D4EB0",
    "func_001D6B10",
    "func_001D6DD0",
    "func_001D71A0",
    "func_001DA290",
    "func_001DF5A0",
    "func_001F4F40",
    "func_001FA570",
    "func_001FABB0",
    "func_001FC9B0",
    "func_001FCB90",
    "func_002061B0",
    "func_0021BD10",
    "func_0021C3F0",
    "func_00225CC0",
    "func_0022EBE0",
}

# Regex for extracting the declared original size from a .s file's nonmatching line.
_NONMATCHING_RE = re.compile(r"^nonmatching\s+\S+,\s+(0x[0-9A-Fa-f]+|\d+)")


def all_asm_functions() -> list[str]:
    """Return deduplicated function names in vram order.

    When two .s files map to the same vram (named syscall stubs and their
    func_XXXXXXXX aliases, e.g. RFU000_FullReset / func_0010B400), only one
    entry is included.  Named (non-func_) forms are preferred because they
    carry the canonical symbol name; the func_ alias is silently dropped.
    """
    entries: list[tuple[int, str]] = []
    for f in ASM_DIR.glob("*.s"):
        name = f.stem
        vram = _vram_from_asm(f)
        entries.append((vram, name))
    entries.sort()

    # Deduplicate by vram: prefer the named form over func_XXXXXXXX aliases.
    seen: dict[int, str] = {}
    for vram, name in entries:
        if vram not in seen:
            seen[vram] = name
        else:
            existing = seen[vram]
            if existing.startswith("func_") and not name.startswith("func_"):
                seen[vram] = name
    return [name for _, name in sorted(seen.items())]


def compute_slot_sizes() -> dict[str, int]:
    """Return a dict mapping function name → slot size in the original binary.

    The slot size is (next_function_vram - this_function_vram), which equals
    the function body size plus any inter-function alignment padding (zero nops)
    that the original CodeWarrior linker inserted between functions.  Using the
    slot size as the truncation target for assembled .s objects ensures that
    trailing gap bytes are included in each filler object, which is required to
    reproduce the exact byte layout of the original binary.
    """
    funcs = all_asm_functions()
    # Build vram → name map for the deduped list.
    vram_list: list[tuple[int, str]] = []
    for name in funcs:
        asm_path = ASM_DIR / f"{name}.s"
        vram = _vram_from_asm(asm_path)
        vram_list.append((vram, name))
    # vram_list is already sorted because all_asm_functions() returns sorted names.

    slot_sizes: dict[str, int] = {}
    for i, (vram, name) in enumerate(vram_list):
        if i + 1 < len(vram_list):
            next_vram = vram_list[i + 1][0]
        else:
            # Last function: slot = its nonmatching declared size (no gap after).
            nm = _nonmatching_size(ASM_DIR / f"{name}.s")
            next_vram = vram + (nm if nm > 0 else 0)
        slot_sizes[name] = next_vram - vram
    return slot_sizes


def _vram_from_asm(path: Path) -> int:
    """Extract the VRAM address of a function from its splat .s file."""
    for line in path.read_text(errors="replace").splitlines()[:20]:
        if "/*" in line:
            try:
                comment = line.split("/*")[1].split("*/")[0].strip()
                parts = comment.split()
                if len(parts) >= 2:
                    return int(parts[1], 16)
            except (ValueError, IndexError):
                pass
    # Fallback: try parsing the filename (func_XXXXXXXX)
    stem = path.stem
    if stem.startswith("func_"):
        try:
            return int(stem[5:], 16)
        except ValueError:
            pass
    return 0


def _nonmatching_size(asm_path: Path) -> int:
    """Return the declared original function size from the nonmatching directive."""
    try:
        for line in asm_path.read_text(errors="replace").splitlines()[:5]:
            m = _NONMATCHING_RE.match(line.strip())
            if m:
                sz_str = m.group(1)
                return int(sz_str, 16) if sz_str.startswith("0x") else int(sz_str)
    except Exception:
        pass
    return 0


def _needs_rebuild(src: Path, dst: Path) -> bool:
    """Return True if dst is missing or older than src."""
    if not dst.exists():
        return True
    return dst.stat().st_mtime < src.stat().st_mtime


def _assemble_from_s(name: str, asm_path: Path, out_path: Path,
                     keep_locals: bool = False,
                     expected_size: int = 0) -> Exception | None:
    """Assemble asm_path -> out_path.  Returns CalledProcessError on failure.

    expected_size: if > 0, passed to _strip() so it can truncate any trailing
        zero-padding that GNU-as adds when rounding .text up to 16-byte boundary.
    """
    extra = ["-L"] if keep_locals else []
    cmd = AS_CMD + extra + [str(asm_path), "-o", str(out_path)]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        return e

    _strip(out_path, expected_size=expected_size)

    if keep_locals:
        # Globalize all .L* symbols so cross-function branch references resolve.
        # Use readelf --syms (not nm) because nm -a does not show .L labels
        # even when assembled with -L.
        try:
            out = subprocess.check_output(
                ["mipsel-linux-gnu-readelf", "--syms", str(out_path)],
                stderr=subprocess.DEVNULL,
            ).decode(errors="replace")
        except subprocess.CalledProcessError:
            return None  # readelf failed; leave object as-is
        local_labels = []
        for line in out.splitlines():
            parts = line.split()
            # readelf --syms format: Num: Value Size Type Bind Vis Ndx Name
            # .L labels are LOCAL NOTYPE symbols
            if len(parts) >= 8 and parts[4] == "LOCAL" and parts[7].startswith(".L"):
                local_labels.append(parts[7])
        if local_labels:
            cmd2 = ["mipsel-linux-gnu-objcopy"]
            for sym in local_labels:
                cmd2 += ["--globalize-symbol", sym]
            cmd2.append(str(out_path))
            subprocess.run(cmd2, check=True)
    return None


def _apply_weaken(name: str, out_path: Path) -> None:
    """Weaken any symbols in WEAKEN_SYMBOLS[name] to avoid multiply-defined errors."""
    syms = WEAKEN_SYMBOLS.get(name)
    if not syms:
        return
    cmd = ["mipsel-linux-gnu-objcopy"]
    for sym in syms:
        cmd += ["--weaken-symbol", sym]
    cmd.append(str(out_path))
    subprocess.run(cmd, check=True)


def assemble_one(name: str, slot_size: int = 0) -> tuple[str, str, Exception | None]:
    """Assemble one .s file into build/filler/<name>.o.  Returns (name, status, err).

    slot_size: the exact number of bytes this function occupies in the original
        binary (next_vram - this_vram).  Passed to _strip() so strip_sections.py
        can resize the .text section to match the original layout, including any
        inter-function zero-nop alignment padding the CodeWarrior linker inserted.
        If 0, no resizing is performed (legacy behaviour).
    """
    asm_path = ASM_DIR / f"{name}.s"
    out_path = FILLER_DIR / f"{name}.o"

    if not asm_path.exists():
        return name, "no_asm", None  # shouldn't happen

    # GPREL force-asm: even if build/obj/ has a compiled copy, use the .s
    # because the mwcc object has R_MIPS_GPREL16 relocations that overflow.
    # SIZE_DRIFT_FORCE_ASM: the build/obj/.o has wrong .text size (mwcc dropped
    # or added instructions); use the .s which has the correct original bytes.
    force_asm = name in GPREL_FORCE_ASM or name in SIZE_DRIFT_FORCE_ASM
    # Cross-label functions need -L + globalize-symbol post-processing.
    keep_locals = name in CROSS_LABEL_FUNCS

    obj_src = OBJ_DIR / f"{name}.o"
    if obj_src.exists() and not force_asm:
        # Use the compiled/asm-matched object from build/obj/.
        if _needs_rebuild(obj_src, out_path):
            shutil.copy2(obj_src, out_path)
            # For matched (mwcc) objects: pass slot_size so that any trailing
            # inter-function gap bytes are appended.  mwcc produces the correct
            # instruction bytes but no trailing nops; the slot_size resize adds
            # them back so the binary layout matches the original.
            _strip(out_path, expected_size=slot_size)
            _apply_weaken(name, out_path)
        return name, "copied", None
    else:
        # Assemble from the splat .s (either no obj/ copy, or forced).
        if not keep_locals and not force_asm and not _needs_rebuild(asm_path, out_path):
            return name, "cached", None
        err = _assemble_from_s(name, asm_path, out_path,
                                keep_locals=keep_locals,
                                expected_size=slot_size)
        if err is not None:
            return name, "asm_error", err
        _apply_weaken(name, out_path)
        if name in GPREL_FORCE_ASM:
            status = "force_asm"
        elif name in SIZE_DRIFT_FORCE_ASM:
            status = "drift_asm"
        else:
            status = "assembled"
        return name, status, None


def _strip(obj: Path, expected_size: int = 0) -> None:
    """Strip empty sections, fix alignment, and optionally truncate .text padding.

    expected_size: if > 0, passed as --expected-size to strip_sections.py so
        it can truncate 16-byte alignment padding from GNU-as assembled objects.
    """
    cmd = [sys.executable, str(STRIP_SCRIPT), str(obj)]
    if expected_size > 0:
        cmd += ["--expected-size", str(expected_size)]
    try:
        subprocess.run(cmd, check=True, capture_output=True)
    except subprocess.CalledProcessError:
        pass  # Non-fatal; mwldmips will report the real error.


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Assemble filler objects for all boot-ELF functions")
    ap.add_argument("--jobs", "-j", type=int, default=8,
                    help="parallel jobs (default 8)")
    ap.add_argument("--clean", action="store_true",
                    help="wipe build/filler/ before building")
    ap.add_argument("--list-order", action="store_true",
                    help="print the link order (one name per line) and exit")
    args = ap.parse_args(argv)

    funcs = all_asm_functions()

    if args.list_order:
        for n in funcs:
            print(n)
        return 0

    if args.clean and FILLER_DIR.exists():
        shutil.rmtree(FILLER_DIR)
    FILLER_DIR.mkdir(parents=True, exist_ok=True)

    # Precompute slot sizes once (avoids re-reading all .s files per function).
    slot_sizes = compute_slot_sizes()

    errors: list[tuple[str, Exception]] = []
    counts = {"copied": 0, "assembled": 0, "cached": 0, "no_asm": 0, "asm_error": 0}

    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = {pool.submit(assemble_one, n, slot_sizes.get(n, 0)): n for n in funcs}
        for fut in as_completed(futures):
            name, status, err = fut.result()
            counts[status] = counts.get(status, 0) + 1
            if err is not None:
                errors.append((name, err))
                print(f"  ERROR assembling {name}: {err}", file=sys.stderr)

    total = len(funcs)
    print(
        f"[fill_unmatched] {total} functions: "
        f"{counts['assembled']} assembled, "
        f"{counts.get('force_asm', 0)} force-asm (gprel), "
        f"{counts.get('drift_asm', 0)} force-asm (size-drift), "
        f"{counts['copied']} copied from obj/, "
        f"{counts['cached']} cached, "
        f"{counts.get('asm_error', 0)} errors"
    )
    if errors:
        print(f"[fill_unmatched] {len(errors)} assembly error(s) — link will likely fail",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
