#!/usr/bin/env python3
"""Assemble all 3149 boot-ELF functions into build/filler/*.o for linking.

For each function that is NOT covered by a compiled build/obj/*.o:
  • Assemble its splat-generated .s file (build/asm/matchings/main/code/<name>.s)
    into build/filler/<name>.o using mipsel-linux-gnu-as -march=r5900.
  • Strip any empty .text/.data/.bss sections that mwldmips rejects.

For each function that IS covered by a compiled build/obj/*.o (our decompiled
C, or an asm-matched .c wrapper):
  • Copy it to build/filler/<name>.o and strip empty sections there too,
    so the linker can pull everything from one flat directory.

The result is a build/filler/ directory containing one .o per function,
covering all 3149 boot-ELF functions, ready for mwldmips.

Usage (run INSIDE the exterm-toolchain container, repo at /work):
    python3 tools/decomp/fill_unmatched.py [--jobs N] [--clean]

Outside the container (via Apple `container` CLI):
    container run --rm -v "$PWD:/work" -w /work exterm-toolchain \\
        python3 tools/decomp/fill_unmatched.py

The script is idempotent — re-running only rebuilds stale or missing objects.
Pass --clean to wipe build/filler/ first.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASM_DIR = ROOT / "build" / "asm" / "matchings" / "main" / "code"
OBJ_DIR = ROOT / "build" / "obj"
FILLER_DIR = ROOT / "build" / "filler"
STRIP_SCRIPT = ROOT / "tools" / "decomp" / "strip_sections.py"

# Assembler invocation (same flags as build.py's assemble_cmd).
# -march=r5900 sets the EE flag so mipsel-linux-gnu-readelf/objcopy handle
# EE-specific instructions correctly.
AS_CMD = [
    "mipsel-linux-gnu-as",
    "-march=r5900",
    str(ROOT / "config" / "asm_prelude.inc"),
    str(ROOT / "build" / "macro.inc"),
]

# Functions that must be assembled with -L (keep local labels) and then have
# all .L* labels globalized, because branches from OTHER functions reference
# labels defined inside these functions' .s files.  Without this the linker
# would see undefined .L00XXXXXX references.
CROSS_LABEL_FUNCS = {
    "func_00140004",
    "func_001C2FF0",
    "func_00200004",
    "func_00201000",
}

# Functions that have R_MIPS_GPREL16 relocations in their build/obj/*.o (mwcc
# compiled) that overflow the ±32KB $gp window at link time.  We fall back to
# assembling from the splat .s instead, which uses LUI+ADDIU (no GP-relative).
# This list was generated by running mwldmips and collecting all GP overflow errors.
GPREL_FORCE_ASM = {
    # Original 4 (identified in first link attempt):
    "func_00102600",
    "func_0011FD78",
    "func_00120AD0",
    "func_001B0070",
    # Additional 107 discovered in subsequent link (obj/ compiled with GP-relative):
    "func_001289C0",
    "func_00128C10",
    "func_0012A5D0",
    "func_0012E560",
    "func_00131740",
    "func_001333F0",
    "func_00133FD0",
    "func_00137920",
    "func_00138540",
    "func_0013D490",
    "func_00140760",
    "func_001418F0",
    "func_00141F00",
    "func_001434C0",
    "func_00145210",
    "func_001469B0",
    "func_001475A0",
    "func_0014BB10",
    "func_0014C2E0",
    "func_0014D3B0",
    "func_0014D7C0",
    "func_0014ED10",
    "func_0014FBC0",
    "func_001516B0",
    "func_00153770",
    "func_00153A10",
    "func_00154040",
    "func_00154740",
    "func_00158810",
    "func_00158EC0",
    "func_00159210",
    "func_00159620",
    "func_00159970",
    "func_00159B90",
    "func_0015A070",
    "func_0015AC00",
    "func_0015C420",
    "func_00161790",
    "func_001647D0",
    "func_0016D130",
    "func_00173E60",
    "func_00180850",
    "func_00181730",
    "func_0018ABA0",
    "func_00198440",
    "func_001BB520",
    "func_001BBDA0",
    "func_001BC960",
    "func_001BD9F0",
    "func_001BDFC0",
    "func_001BE6C0",
    "func_001BECC0",
    "func_001BF3C0",
    "func_001BF6B0",
    "func_001C0004",
    "func_001C02E0",
    "func_001C06E0",
    "func_001C1A80",
    "func_001CB9B0",
    "func_001D0F20",
    "func_001D1C50",
    "func_001D1F20",
    "func_001D1F80",
    "func_001D1FF0",
    "func_001D2040",
    "func_001D2090",
    "func_001D21E0",
    "func_001D2300",
    "func_001D3F60",
    "func_001D40E0",
    "func_001D4440",
    "func_001D49D0",
    "func_001D8130",
    "func_001D8340",
    "func_001D8690",
    "func_001D88B0",
    "func_001D89D0",
    "func_001DA6A0",
    "func_001DD7B0",
    "func_001DDB70",
    "func_001DDE10",
    "func_001DE920",
    "func_001DF180",
    "func_001DF600",
    "func_001DFA40",
    "func_001E1E60",
    "func_001E7D20",
    "func_001E9280",
    "func_001E9E60",
    "func_001FCBD0",
    "func_001FCE30",
    "func_001FD950",
    "func_001FE6B0",
    "func_001FE7C0",
    "func_001FE8D0",
    "func_001FEE60",
    "func_00206BF0",
    "func_00207350",
    "func_00207BB0",
    "func_00207D00",
    "func_002134C0",
    "func_00219550",
    "func_0021B180",
    "func_0021B550",
    "func_0021B840",
    "func_00228C90",
    "func_002293B0",
}

# Symbols in these objects that must be weakened to avoid multiply-defined
# errors when the same symbol is also declared as a BSS global in a compiled
# src/*.c file.  Maps object-stem → list of symbol names to weaken.
WEAKEN_SYMBOLS: dict[str, list[str]] = {
    "func_00271DF8": ["D_00275670"],
}


def all_asm_functions() -> list[str]:
    """Return all function names from build/asm/matchings/main/code/*.s, vram-ordered."""
    entries: list[tuple[int, str]] = []
    for f in ASM_DIR.glob("*.s"):
        name = f.stem
        vram = _vram_from_asm(f)
        entries.append((vram, name))
    entries.sort()
    return [name for _, name in entries]


def _vram_from_asm(path: Path) -> int:
    """Extract the VRAM address of a function from its splat .s file."""
    for line in path.read_text(errors="replace").splitlines()[:20]:
        if "/*" in line:
            try:
                comment = line.split("/*")[1].split("*/")[0].strip()
                parts = comment.split()
                if len(parts) >= 2:
                    return int(parts[1], 16)
            except (ValueError, IndexError):
                pass
    # Fallback: try parsing the filename (func_XXXXXXXX)
    stem = path.stem
    if stem.startswith("func_"):
        try:
            return int(stem[5:], 16)
        except ValueError:
            pass
    return 0


def _needs_rebuild(src: Path, dst: Path) -> bool:
    """Return True if dst is missing or older than src."""
    if not dst.exists():
        return True
    return dst.stat().st_mtime < src.stat().st_mtime


def _assemble_from_s(name: str, asm_path: Path, out_path: Path,
                     keep_locals: bool = False) -> Exception | None:
    """Assemble asm_path -> out_path.  Returns CalledProcessError on failure."""
    extra = ["-L"] if keep_locals else []
    cmd = AS_CMD + extra + [str(asm_path), "-o", str(out_path)]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        return e

    _strip(out_path)

    if keep_locals:
        # Globalize all .L* symbols so cross-function branch references resolve.
        # Use readelf --syms (not nm) because nm -a does not show .L labels
        # even when assembled with -L.
        try:
            out = subprocess.check_output(
                ["mipsel-linux-gnu-readelf", "--syms", str(out_path)],
                stderr=subprocess.DEVNULL,
            ).decode(errors="replace")
        except subprocess.CalledProcessError:
            return None  # readelf failed; leave object as-is
        local_labels = []
        for line in out.splitlines():
            parts = line.split()
            # readelf --syms format: Num: Value Size Type Bind Vis Ndx Name
            # .L labels are LOCAL NOTYPE symbols
            if len(parts) >= 8 and parts[4] == "LOCAL" and parts[7].startswith(".L"):
                local_labels.append(parts[7])
        if local_labels:
            cmd2 = ["mipsel-linux-gnu-objcopy"]
            for sym in local_labels:
                cmd2 += ["--globalize-symbol", sym]
            cmd2.append(str(out_path))
            subprocess.run(cmd2, check=True)
    return None


def _apply_weaken(name: str, out_path: Path) -> None:
    """Weaken any symbols in WEAKEN_SYMBOLS[name] to avoid multiply-defined errors."""
    syms = WEAKEN_SYMBOLS.get(name)
    if not syms:
        return
    cmd = ["mipsel-linux-gnu-objcopy"]
    for sym in syms:
        cmd += ["--weaken-symbol", sym]
    cmd.append(str(out_path))
    subprocess.run(cmd, check=True)


def assemble_one(name: str) -> tuple[str, str, Exception | None]:
    """Assemble one .s file into build/filler/<name>.o.  Returns (name, status, err)."""
    asm_path = ASM_DIR / f"{name}.s"
    out_path = FILLER_DIR / f"{name}.o"

    if not asm_path.exists():
        return name, "no_asm", None  # shouldn't happen

    # GPREL force-asm: even if build/obj/ has a compiled copy, use the .s
    # because the mwcc object has R_MIPS_GPREL16 relocations that overflow.
    force_asm = name in GPREL_FORCE_ASM
    # Cross-label functions need -L + globalize-symbol post-processing.
    keep_locals = name in CROSS_LABEL_FUNCS

    obj_src = OBJ_DIR / f"{name}.o"
    if obj_src.exists() and not force_asm:
        # Use the compiled/asm-matched object from build/obj/.
        if _needs_rebuild(obj_src, out_path):
            shutil.copy2(obj_src, out_path)
            _strip(out_path)
            _apply_weaken(name, out_path)
        return name, "copied", None
    else:
        # Assemble from the splat .s (either no obj/ copy, or forced).
        if not keep_locals and not force_asm and not _needs_rebuild(asm_path, out_path):
            return name, "cached", None
        err = _assemble_from_s(name, asm_path, out_path, keep_locals=keep_locals)
        if err is not None:
            return name, "asm_error", err
        _apply_weaken(name, out_path)
        status = "force_asm" if force_asm else "assembled"
        return name, status, None


def _strip(obj: Path) -> None:
    """Strip empty .text/.data/.bss sections from a GNU-as ELF object."""
    try:
        subprocess.run(
            [sys.executable, str(STRIP_SCRIPT), str(obj)],
            check=True,
            capture_output=True,
        )
    except subprocess.CalledProcessError:
        pass  # Non-fatal; mwldmips will report the real error.


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Assemble filler objects for all boot-ELF functions")
    ap.add_argument("--jobs", "-j", type=int, default=8,
                    help="parallel jobs (default 8)")
    ap.add_argument("--clean", action="store_true",
                    help="wipe build/filler/ before building")
    ap.add_argument("--list-order", action="store_true",
                    help="print the link order (one name per line) and exit")
    args = ap.parse_args(argv)

    funcs = all_asm_functions()

    if args.list_order:
        for n in funcs:
            print(n)
        return 0

    if args.clean and FILLER_DIR.exists():
        shutil.rmtree(FILLER_DIR)
    FILLER_DIR.mkdir(parents=True, exist_ok=True)

    errors: list[tuple[str, Exception]] = []
    counts = {"copied": 0, "assembled": 0, "cached": 0, "no_asm": 0, "asm_error": 0}

    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = {pool.submit(assemble_one, n): n for n in funcs}
        for fut in as_completed(futures):
            name, status, err = fut.result()
            counts[status] = counts.get(status, 0) + 1
            if err is not None:
                errors.append((name, err))
                print(f"  ERROR assembling {name}: {err}", file=sys.stderr)

    total = len(funcs)
    print(
        f"[fill_unmatched] {total} functions: "
        f"{counts['assembled']} assembled, "
        f"{counts.get('force_asm', 0)} force-asm, "
        f"{counts['copied']} copied from obj/, "
        f"{counts['cached']} cached, "
        f"{counts.get('asm_error', 0)} errors"
    )
    if errors:
        print(f"[fill_unmatched] {len(errors)} assembly error(s) — link will likely fail",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
