#!/usr/bin/env python3
"""Link the Extermination boot ELF from filler + matched objects via mwldmips.

This script:
  1. (Optionally) runs fill_unmatched.py to ensure build/filler/ is current.
  2. Generates config/SCUS_971.12.lcf with the exact per-function link order
     derived from vram addresses in the splat .s files.
  3. Generates build/link_objects.txt with the path to each .o file
     (mwldmips accepts @file to read a list of objects).
  4. Invokes mwldmips.exe via qemu-i386 + wibo32 inside the container.
  5. Compares the loadable region of the output ELF against the original.

Run this INSIDE the exterm-toolchain container (repo at /work), or via:
    container run --rm -v "$PWD:/work" -w /work exterm-toolchain \\
        python3 tools/decomp/link.py [--no-fill] [--dry-run]

Flags:
  --no-fill       skip fill_unmatched.py (use existing build/filler/)
  --dry-run       generate LCF + object list but don't invoke mwldmips
  --verify        compare linked ELF loadable bytes vs original (default on)
  --no-verify     skip byte comparison
"""
from __future__ import annotations

import argparse
import struct
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONFIG = ROOT / "config"
BUILD = ROOT / "build"
ELF_OUT = ROOT / "elf" / "SCUS_971.12.elf"
ORIG_ELF = CONFIG / "SCUS_971.12"
LCF = CONFIG / "SCUS_971.12.lcf"
OBJ_LIST = BUILD / "link_objects.txt"
ASM_DIR = BUILD / "asm" / "matchings" / "main" / "code"
FILLER_DIR = BUILD / "filler"

MWLD = [
    "qemu-i386",
    "tools/bin/wibo32",
    "tools/mwccps2/mwldmips.exe",
]

# Original ELF layout (from CLAUDE.md / target-identity):
#   File offset 0x300 → vram 0x00100000, filesz 0x175b00
ORIG_LOAD_OFFSET = 0x300
ORIG_LOAD_VRAM = 0x00100000
ORIG_LOAD_FILESZ = 0x175B00


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _vram_from_asm(path: Path) -> int:
    for line in path.read_text(errors="replace").splitlines()[:20]:
        if "/*" in line:
            try:
                comment = line.split("/*")[1].split("*/")[0].strip()
                parts = comment.split()
                if len(parts) >= 2:
                    return int(parts[1], 16)
            except (ValueError, IndexError):
                pass
    stem = path.stem
    if stem.startswith("func_"):
        try:
            return int(stem[5:], 16)
        except ValueError:
            pass
    return 0


def sorted_functions() -> list[str]:
    """Return all function names in vram order."""
    entries: list[tuple[int, str]] = []
    for f in ASM_DIR.glob("*.s"):
        vram = _vram_from_asm(f)
        entries.append((vram, f.stem))
    entries.sort()
    return [name for _, name in entries]


# ---------------------------------------------------------------------------
# LCF generation
# ---------------------------------------------------------------------------

LCF_HEADER = """\
#\t===========================================================================
#\tSCUS_971.12.lcf -- Metrowerks CodeWarrior linker command file
#\tExtermination (SCUS-97112, PS2, Metrowerks CodeWarrior mwccps2 2.3.1.01)
#\tGENERATED by tools/decomp/link.py -- do not edit by hand.
#\t===========================================================================

MEMORY
{{
\t#\tMain segment: one PROGBITS LOAD from 0x00100000.
\t#\tLENGTH = 0 lets mwldmips auto-size.
\tmain  (RWX) : ORIGIN = 0x00100000, LENGTH = 0

\t#\tOverlay arena -- not yet linked (placeholder).
\toverlay_arena (RWX) : ORIGIN = 0x00823500, LENGTH = 0

\theap  (RW)  : ORIGIN = AFTER(main), LENGTH = 0
}}

KEEP_SECTION
{{
\t.vutext,
\t.vudata,
\t.vubss
}}

SECTIONS
{{
\t#\t---- ELF scalars ----
\t_stack      = 0x01F00000;
\t_stack_size = 0x00080000;
\t_heap_size  = -1;
\t_align_segment = 0x80;

\t#\t$gp is fixed by crt0: lui 0x28 / addiu -0x2C90 = 0x0027D370
\t_gp = 0x0027D370;

\t#\t---- Absolute address symbols (splat-auto undefined symbols) ----
\t#\tThese are BSS, IOP, and hardware addresses referenced in the code.
{abs_syms}
\t.main :
\t{{
\t\t#\t============================================================
\t\t#\tTEXT -- all {n_funcs} boot-ELF functions in vram order
\t\t#\tNo alignment directives: section starts at ORIGIN (0x00100000)
\t\t#\twhich is already instruction-aligned.  Any ALIGN() or ALIGNALL()
\t\t#\there causes mwldmips to insert padding words before the first
\t\t#\tfunction, shifting all subsequent vram addresses.
\t\t#\t============================================================
"""

LCF_MIDDLE = """\
\t\t#\t============================================================
\t\t#\tDATA / RODATA / SDATA / LITERALS
\t\t#\t============================================================
\t\t__data_start = .;

\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\t*  (.data)

\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\t*  (.vudata)

\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\t*  (.rodata)

\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\t*  (.rdata)

\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\t*  (.lit4)

\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\t*  (.lit8)

\t\t. = ALIGN(0x10);
\t\tALIGNALL(4);
\t\t*  (.init)

\t\t. = ALIGN(0x10);
\t\tALIGNALL(4);
\t\t__static_init     = .;
\t\t*  (.ctor)
\t\t__static_init_end = .;

\t\t. = ALIGN(0x10);
\t\tALIGNALL(4);
\t\t*  (.vtables)

\t\t. = ALIGN(0x10);
\t\t__exception_table_start__ = .;
\t\tEXCEPTION
\t\t__exception_table_end__   = .;

\t\t__data_end  = .;
\t\t__data_size = __data_end - __data_start;

\t\t#\t============================================================
\t\t#\tLITERAL POOL / SDATA
\t\t#\t============================================================
\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\tLITERAL

\t\t. = ALIGN(0x80);
\t\tALIGNALL(4);
\t\t*  (.sdata)

\t\t#\t============================================================
\t\t#\tBSS / SBSS
\t\t#\t============================================================
\t\t. = ALIGN(0x80);
\t\t_fbss = .;
\t\tALIGNALL(4);
\t\t*  (.sbss)
\t\tALIGNALL(4);
\t\t*  (.scommon)
\t\tALIGNALL(4);
\t\t*  (SCOMMON)

\t\t__bss_start = .;
\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\t*  (.bss)
\t\tALIGNALL(8);
\t\t*  (.common)
\t\tALIGNALL(8);
\t\t*  (COMMON)
\t\t. = ALIGN(0x80);
\t\tALIGNALL(8);
\t\t*  (.vubss)
\t\tALIGNALL(8);
\t\t__bss_end  = .;
\t\t__bss_size = __bss_end - __bss_start;

\t\t. = ALIGN(_align_segment);

\t}} > main

\t.heap :
\t{{
\t\tend  = .;
\t\t_end = .;
\t}} > heap
}}

#\t===========================================================================
#\tend of SCUS_971.12.lcf
#\t===========================================================================
"""


def _load_abs_syms() -> str:
    """Load absolute-address symbols from splat auto files for inclusion in the LCF.

    Reads build/undefined_syms_auto.txt and build/undefined_funcs_auto.txt, plus
    hard-codes a few EE exception-vector addresses that splat doesn't know about.

    Also auto-derives addresses for any symbol whose name encodes its address in
    the pattern D_XXXXXXXX or func_XXXXXXXX (hex suffix = vram address).  This
    handles data-table references that splat named with a D_ prefix and function
    references to addresses outside the boot ELF (EE kernel entry vectors, IOP RAM,
    overlay addresses).

    Returns a block of '\tNAME = 0xADDR;\n' lines for insertion into SECTIONS.
    """
    import re as _re

    syms: dict[str, str] = {}

    # Hard-code EE exception/interrupt vector entry points.
    for name, addr in [
        ("func_00000008", "0x00000008"),
        ("func_0000000C", "0x0000000C"),
        ("func_00000010", "0x00000010"),
        ("func_00000014", "0x00000014"),
        ("func_0000001C", "0x0000001C"),
        ("func_00000804", "0x00000804"),
        ("func_0C000004", "0x0C000004"),
    ]:
        syms[name] = addr

    # Load splat's auto-generated undefined-symbol files.
    for auto_path in (
        BUILD / "undefined_syms_auto.txt",
        BUILD / "undefined_funcs_auto.txt",
    ):
        if not auto_path.exists():
            continue
        for line in auto_path.read_text().splitlines():
            m = _re.match(r"^(\S+)\s*=\s*(0x[0-9A-Fa-f]+);", line)
            if m:
                syms[m.group(1)] = m.group(2)

    # Auto-derive any D_XXXXXXXX or func_XXXXXXXX symbol whose address is encoded
    # in the name itself.  This covers symbols that appear as link-time references
    # but are absent from the auto files (often because they were "defined" by a
    # function that was renamed by splat, e.g. a data table named func_00230800).
    # We add ALL such deducible symbols rather than just the ones that errored,
    # because the set may change as more functions are matched.
    _name_re = _re.compile(r"^(?:D_|func_)([0-9A-Fa-f]{4,8})$")
    for auto_path in (
        BUILD / "undefined_syms_auto.txt",
        BUILD / "undefined_funcs_auto.txt",
    ):
        if not auto_path.exists():
            continue
        for line in auto_path.read_text().splitlines():
            m = _name_re.match(line.split()[0]) if line.split() else None
            if m:
                name = line.split()[0]
                addr = "0x{:08X}".format(int(m.group(1), 16))
                if name not in syms:
                    syms[name] = addr

    # Scan ALL .s files for D_XXXXXXXX and low-address func_XXXXXXXX references.
    # Any symbol whose name encodes its address can be provided as an absolute
    # definition — this covers thousands of BSS, IOP, hardware-register, and
    # data-table references that are absent from the auto files.
    _d_re = _re.compile(r"\bD_([0-9A-Fa-f]{7,8})\b")
    _f_re = _re.compile(r"\bfunc_([0-9A-Fa-f]{7,8})\b")
    for asm_file in ASM_DIR.glob("*.s"):
        content = asm_file.read_text(errors="replace")
        for m in _d_re.finditer(content):
            name = m.group(0)
            if name not in syms:
                syms[name] = "0x{:08X}".format(int(m.group(1), 16))
        for m in _f_re.finditer(content):
            name = m.group(0)
            addr = int(m.group(1), 16)
            # Only add func_ symbols that are OUTSIDE the boot ELF range —
            # those inside will be provided by the linked .o files.
            if addr < 0x00100000 or addr > 0x00275B00:
                if name not in syms:
                    syms[name] = "0x{:08X}".format(addr)

    if not syms:
        return ""
    lines = [f"\t{name} = {addr};\n" for name, addr in sorted(syms.items())]
    return "".join(lines)


def generate_lcf(funcs: list[str]) -> str:
    """Generate the full LCF content."""
    # LCF_HEADER uses {{/}} to escape braces for .format(); LCF_MIDDLE uses
    # single braces and is appended after a simple replace to avoid double-
    # brace confusion.
    abs_syms = _load_abs_syms()
    header = LCF_HEADER.format(n_funcs=len(funcs), abs_syms=abs_syms)
    # LCF_MIDDLE was written with {{ }} so it can share a .format() call;
    # normalize it here so the output has literal single-brace LCF syntax.
    middle = LCF_MIDDLE.replace("{{", "{").replace("}}", "}")
    obj_lines = "".join(f"\t\t{name}.o (.text)\n" for name in funcs)
    return header + obj_lines + "\n" + middle


# ---------------------------------------------------------------------------
# ELF comparison
# ---------------------------------------------------------------------------

def find_load_segment(elf_path: Path) -> tuple[int, int, int]:
    """Return (file_offset, vaddr, filesz) of the first PT_LOAD segment."""
    data = elf_path.read_bytes()
    # ELF32 little-endian header
    e_phoff = struct.unpack_from("<I", data, 0x1c)[0]
    e_phentsize = struct.unpack_from("<H", data, 0x2a)[0]
    e_phnum = struct.unpack_from("<H", data, 0x2c)[0]
    PT_LOAD = 1
    for i in range(e_phnum):
        off = e_phoff + i * e_phentsize
        p_type = struct.unpack_from("<I", data, off)[0]
        if p_type == PT_LOAD:
            p_offset = struct.unpack_from("<I", data, off + 4)[0]
            p_vaddr = struct.unpack_from("<I", data, off + 8)[0]
            p_filesz = struct.unpack_from("<I", data, off + 16)[0]
            return p_offset, p_vaddr, p_filesz
    raise ValueError(f"No PT_LOAD segment found in {elf_path}")


def compare_elf(linked: Path, original: Path) -> bool:
    """Compare the loadable content of linked vs original.  Return True if identical."""
    if not original.exists():
        print("[verify] original ELF not found — skip comparison")
        return True

    try:
        link_off, link_vaddr, link_filesz = find_load_segment(linked)
        orig_off, orig_vaddr, orig_filesz = find_load_segment(original)
    except (ValueError, struct.error) as e:
        print(f"[verify] could not parse ELF headers: {e}")
        return False

    print(f"[verify] linked  LOAD: offset=0x{link_off:x}, vaddr=0x{link_vaddr:x}, filesz=0x{link_filesz:x}")
    print(f"[verify] original LOAD: offset=0x{orig_off:x}, vaddr=0x{orig_vaddr:x}, filesz=0x{orig_filesz:x}")

    link_data = linked.read_bytes()
    orig_data = original.read_bytes()

    compare_size = min(link_filesz, orig_filesz)
    link_content = link_data[link_off: link_off + compare_size]
    orig_content = orig_data[orig_off: orig_off + compare_size]

    if link_content == orig_content:
        print(f"[verify] PASS — 0x{compare_size:x} loadable bytes are identical")
        if link_filesz != orig_filesz:
            print(f"[verify] NOTE: filesz differs (linked 0x{link_filesz:x} vs orig 0x{orig_filesz:x})")
        return True
    else:
        diffs = sum(1 for a, b in zip(link_content, orig_content) if a != b)
        print(f"[verify] FAIL — {diffs} byte(s) differ in 0x{compare_size:x}-byte loadable region")
        # Show first difference
        for i, (a, b) in enumerate(zip(link_content, orig_content)):
            if a != b:
                vram = (orig_vaddr + i) if orig_vaddr else i
                print(f"[verify]   first diff at 0x{vram:08x}: linked=0x{a:02x} orig=0x{b:02x}")
                break
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Link the Extermination boot ELF via mwldmips")
    ap.add_argument("--no-fill", action="store_true",
                    help="skip fill_unmatched.py (use existing build/filler/)")
    ap.add_argument("--dry-run", action="store_true",
                    help="generate LCF + object list but don't invoke mwldmips")
    ap.add_argument("--no-verify", action="store_true",
                    help="skip comparison against original ELF")
    args = ap.parse_args(argv)

    # Step 1: fill unmatched
    if not args.no_fill:
        print("[link] running fill_unmatched.py ...")
        r = subprocess.run(
            [sys.executable,
             str(ROOT / "tools" / "decomp" / "fill_unmatched.py"),
             "--jobs", "8"],
            cwd=ROOT,
        )
        if r.returncode != 0:
            print("[link] fill_unmatched.py failed", file=sys.stderr)
            return 1

    # Step 2: generate LCF
    funcs = sorted_functions()
    print(f"[link] {len(funcs)} functions in link order")
    lcf_text = generate_lcf(funcs)
    LCF.write_text(lcf_text)
    print(f"[link] wrote {LCF.relative_to(ROOT)}")

    # Step 3: generate object list
    missing = []
    obj_paths = []
    for name in funcs:
        obj = FILLER_DIR / f"{name}.o"
        if not obj.exists():
            missing.append(name)
        obj_paths.append(str(obj.relative_to(ROOT)))

    if missing:
        print(f"[link] WARNING: {len(missing)} objects missing from build/filler/:",
              file=sys.stderr)
        for m in missing[:10]:
            print(f"  {m}", file=sys.stderr)
        if len(missing) > 10:
            print(f"  ... and {len(missing) - 10} more", file=sys.stderr)

    OBJ_LIST.write_text("\n".join(obj_paths) + "\n")
    print(f"[link] wrote {OBJ_LIST.relative_to(ROOT)} ({len(obj_paths)} entries)")

    if args.dry_run:
        print("[link] dry-run: stopping before mwldmips invocation")
        return 0

    # Step 4: link
    (ROOT / "elf").mkdir(exist_ok=True)
    cmd = (MWLD + [
        "-map",
        "-nostdlib",
        "-m", "_start",
        "-nodead",
        "-o", str(ELF_OUT.relative_to(ROOT)),
        str(LCF.relative_to(ROOT)),
        f"@{OBJ_LIST.relative_to(ROOT)}",
    ])
    print(f"[link] invoking mwldmips: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=ROOT)
    if result.returncode != 0:
        print(f"[link] mwldmips failed (exit {result.returncode})", file=sys.stderr)
        # Still try verify if output exists
        if not ELF_OUT.exists():
            return 1
    else:
        print(f"[link] mwldmips succeeded → {ELF_OUT.relative_to(ROOT)}")

    # Step 5: verify
    if not args.no_verify:
        ok = compare_elf(ELF_OUT, ORIG_ELF)
        return 0 if ok else 2

    return result.returncode


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
